project:
  type: website
  title: "Meta-analysis of the machine learning operations open source ecosystem"

website:
  navbar:
    background: '#532d8e'
    search: true
    left:
      - text: "Proposal"
        file: index.qmd
