project:
  type: book

book:
  title: "Meta-analysis of the open source ecosystem of machine learning operations"
  author: "Isabel Zimmerman"
  date: "10/20/2022"
  chapters:
    - index.qmd
    - sections/proposal.qmd
    - sections/rough.qmd

# bibliography: references.bib

format:
  html:
    theme: pulse
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png