---
title: "Project proposal"
format:
  html:
    toc: true
---

## Motivation

Machine learning operations, or MLOps, is a set of practices to deploy and maintain machine learning models in production reliably and efficiently. These practices are part of the machine learning lifecycle, occurring after training and tuning a model. While not every MLOps practice is applicable at scale for every team, these best practices can elevate any size of project.

## Specific Objectives

This project seeks to provide an overview

## Literature Review

MLOps frameworks have a broad scope. Projects generally fall into a few different categories:

  - Pipelines
  - Workflow management
  - Experiment tracking
  - Model versioning
  - Model deployment
  - Model monitoring
  - All-in-one

MLOps is difficult for a myriad of reasons. One common pain point is that data science is highly experimental, while deploying to a production environment requires strict software engineering practices. To help ease this pain point, APIs are commonly used to deploy models due to their stability and simplicity. APIs can be tested, and they act nearly identically in every architecture. This allows for software engineering practices to be applied to APIs. They are also easy to configure and update, giving data scientists agility to retrain and update models as needed.

## Methodology of the Proposed Research Work

```{python}
#| echo: false
#| output: true
 
import polars

raw = polars.read_csv("../data/oss_mlops.csv")

print(f"number of rows: {raw.height}")
raw.head(3)
```


## The interdisciplinary nature of your proposed research

Machine learning operations has an interdisciplinary nature. In fact, many of the reasons it is so difficult is due to the span of knowledge necessary for successful operationalization of models. It is necessary to have knowledge of data wrangling and statistical modeling to create the model (as taught in *CAP 5320* - Data Wrangling and Exploratory Data Analysis and *CAP 5765* - Computational Data Analysis), along with knowledge of software engineering best practices to have a stable deployment (*CEN 5035* - Advanced Software Engineering) and visualization skills to continually monitor model performance (*CAP 5735* - Data Visualization and Reproducible Research).

## Deliverables

The intended deliverable of this project is a paper that does an analysis.

## Further work

The discoveries from this work could easily be extended further. One possible outcome would be a second paper in the style of "Ten simple rules for X", where the topic would be related to machine learning operations. Another extension could be an opinionated workflow for a specific task built with a selection of the tools analyzed; this could also include multiple open source contributions to these tools.

## Several key literature references or sources (IEEE Citation Style)

Books:

-   [*Designing Machine Learning Systems*](https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/) by Chip Huyen

Articles:

-   ["Machine Learning Operations (MLOps): Overview, Definition, and Architecture"](https://arxiv.org/abs/2205.02302) by Kreuzberger et al
-   ["Towards Observability for Production Machine Learning Pipelines"](https://arxiv.org/pdf/2108.13557.pdf) by Shankar et al
-   ["The ML Test Score: A Rubric for ML Production Readiness and Technical Debt Reduction"](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/aad9f93b86b7addfea4c419b9100c6cdd26cacea.pdf) by Breck et al
-   ["Operationalizing Machine Learning: An Interview Study"](https://arxiv.org/pdf/2209.09125.pdf) by Shankar et al
-   ["Context: The Missing Piece in the Machine Learning Lifecycle"](https://rise.cs.berkeley.edu/wp-content/uploads/2019/02/Flor_CMI_18_CameraReady.pdf)
-   ["A Comparison of Open Source Tools for Data Science"](http://jisar.org/2016-9/n2/JISARv9n2p4.pdf)
-   ["Open-Source Network Simulation Tools: An Overview"](https://www.researchgate.net/profile/Mangesh-Ghonge/publication/249998863_Open-Source_Network_Simulation_Tools_An_Overview/links/0046351e8eec948156000000/Open-Source-Network-Simulation-Tools-An-Overview.pdf)
-   ["Demystifying mlops and presenting a recipe for the selection of open-source tools"](https://www.mdpi.com/2076-3417/11/19/8861)


Web content:

-   [*How ML Breaks: A Decade of Outages for One Large ML Pipeline*](https://www.youtube.com/watch?v=hBMHohkRgAA) by Papasian and Underwood
-   [*Google's Practitioners Guide to MLOps*](https://services.google.com/fh/files/misc/practitioners_guide_to_mlops_whitepaper.pdf) by Salama et al
-   [*MLOps Is a Mess But That's to be Expected*](https://www.mihaileric.com/posts/mlops-is-a-mess/)
